using Haworks.Privacy.Application;
using Haworks.Privacy.Infrastructure;
using Haworks.Privacy.Infrastructure.Persistence;
using Haworks.BuildingBlocks.Authentication;
using Haworks.BuildingBlocks.Extensions;
using Haworks.BuildingBlocks.Persistence;
using Haworks.BuildingBlocks.Startup;
using Microsoft.EntityFrameworkCore;
using Serilog;

var builder = WebApplication.CreateBuilder(args);

// Add service defaults & Aspire components
builder.AddServiceDefaults();

// Add Serilog — explicit console sink since no appsettings.json exists
builder.Host.UseSerilog((context, loggerConfiguration) => loggerConfiguration
    .ReadFrom.Configuration(context.Configuration)
    .WriteTo.Console());

// Add layers
builder.Services.AddApplication();
builder.Services.AddInfrastructure(builder.Configuration, builder.Environment);
builder.Services.AddStartupTaskRunner();

builder.Services.AddJwksAuthentication(builder.Configuration);
builder.Services.AddHttpContextAccessor();

builder.Services.AddRateLimiter(options =>
{
    options.AddPolicy("api", context =>
    {
        // Partition by authenticated user ID so limits are per-user, not global.
        var userId = context.User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value
                     ?? context.User.FindFirst("sub")?.Value
                     ?? context.Connection.RemoteIpAddress?.ToString()
                     ?? "anonymous";

        return System.Threading.RateLimiting.RateLimitPartition.GetFixedWindowLimiter(
            partitionKey: userId,
            factory: _ => new System.Threading.RateLimiting.FixedWindowRateLimiterOptions
            {
                PermitLimit = 100,
                Window = TimeSpan.FromMinutes(1)
            });
    });
});

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddHealthChecks().AddDbHealthCheck<Haworks.Privacy.Infrastructure.Persistence.PrivacyDbContext>();

var app = builder.Build();

// Ensure privacy schema exists before EF migration runs
using (var schemaScope = app.Services.CreateScope())
{
    var db = schemaScope.ServiceProvider.GetRequiredService<PrivacyDbContext>();
    db.Database.ExecuteSqlRaw("CREATE SCHEMA IF NOT EXISTS privacy");
}
app.MigrateDatabase<PrivacyDbContext>();

// Ensure MassTransit outbox tables exist in the privacy schema.
// The EF migration creates them without schema qualifier (landing in public),
// but PrivacyDbContext.HasDefaultSchema("privacy") makes MassTransit query privacy.OutboxState.
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<PrivacyDbContext>();
    try
    {
        db.Database.ExecuteSqlRaw("""
            CREATE TABLE IF NOT EXISTS privacy."OutboxState" (
                "OutboxId" uuid NOT NULL PRIMARY KEY,
                "LockId" uuid NOT NULL,
                "RowVersion" bytea,
                "Created" timestamp with time zone NOT NULL,
                "Delivered" timestamp with time zone,
                "LastSequenceNumber" bigint
            );
            CREATE TABLE IF NOT EXISTS privacy."InboxState" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "MessageId" uuid NOT NULL,
                "ConsumerId" uuid NOT NULL,
                "LockId" uuid NOT NULL,
                "RowVersion" bytea,
                "Received" timestamp with time zone NOT NULL,
                "ReceiveCount" int NOT NULL,
                "ExpirationTime" timestamp with time zone,
                "Consumed" timestamp with time zone,
                "Delivered" timestamp with time zone,
                "LastSequenceNumber" bigint,
                CONSTRAINT "AK_InboxState_MessageId_ConsumerId" UNIQUE ("MessageId", "ConsumerId")
            );
            CREATE TABLE IF NOT EXISTS privacy."OutboxMessage" (
                "SequenceNumber" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "EnqueueTime" timestamp with time zone,
                "SentTime" timestamp with time zone NOT NULL,
                "Headers" text,
                "Properties" text,
                "InboxMessageId" uuid,
                "InboxConsumerId" uuid,
                "OutboxId" uuid,
                "MessageId" uuid NOT NULL,
                "ContentType" text NOT NULL,
                "MessageType" text NOT NULL,
                "Body" text NOT NULL,
                "ConversationId" uuid,
                "CorrelationId" uuid,
                "InitiatorId" uuid,
                "RequestId" uuid,
                "SourceAddress" text,
                "DestinationAddress" text,
                "ResponseAddress" text,
                "FaultAddress" text,
                "ExpirationTime" timestamp with time zone
            );
            """);
    }
    catch (Exception ex)
    {
        var logger = scope.ServiceProvider.GetRequiredService<ILogger<PrivacyDbContext>>();
        logger.LogWarning(ex, "Failed to ensure outbox tables in privacy schema — may already exist");
    }
}



// Configure the HTTP request pipeline
// Temporarily enable detailed errors in all environments to debug 500s
app.UseDeveloperExceptionPage();
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();
app.UseRateLimiter();
app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();
app.MapDefaultEndpoints();

app.Run();

public partial class Program { }
