// <auto-generated />
using Haworks.Catalog.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Haworks.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260526120000_UnitPriceCents")]
    partial class UnitPriceCents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
