// <auto-generated />
#pragma warning disable
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Haworks.Location.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddUniqueAddressIndex : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateIndex(
                name: "IX_Addresses_Unique_Address",
                schema: "location",
                table: "Addresses",
                columns: new[] { "Street", "City", "Postcode", "Country" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Addresses_Unique_Address",
                schema: "location",
                table: "Addresses");
        }
    }
}