// <auto-generated />
#pragma warning disable
using Haworks.Location.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Haworks.Location.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LocationDbContext))]
    [Migration("20260527000000_AddIdempotencyJournalAndUniqueAddress")]
    partial class AddIdempotencyJournalAndUniqueAddress
    {
    }
}
