// <auto-generated />
using Haworks.CheckoutOrchestrator.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Haworks.CheckoutOrchestrator.Infrastructure.Migrations
{
    [DbContext(typeof(CheckoutDbContext))]
    [Migration("20260526120003_TotalAmountCents")]
    partial class TotalAmountCents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
