// <auto-generated />
using Haworks.Payouts.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Haworks.Payouts.Infrastructure.Migrations
{
    [DbContext(typeof(PayoutsDbContext))]
    [Migration("20260526140001_AddSellerProfiles")]
    partial class AddSellerProfiles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
