// <auto-generated />
using Haworks.Payments.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Haworks.Payments.Infrastructure.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    [Migration("20260526140000_AddRenewingTimeoutTokenId")]
    partial class AddRenewingTimeoutTokenId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
